Sprint 17
AndyKruch/iOS-TrackerApp pull request #5
Opened 2023-09-27 10:46 UTC by AndyKruch

Добрый день! 

Прошу проверить ДЗ по 17 спринту.

Спасибо!

2023-09-27 18:38 UTC, protos17 requested changes

2023-09-27 18:38 UTC, protos17 commented on iOS-TrackerApp/iOS-TrackerApp/Modules/Statistics/StatisticsViewController.swift
> +        }
Лучше написать:

statisticsStack.isHidden = trackers.isEmpty

2023-09-27 18:38 UTC, protos17 commented on iOS-TrackerApp/iOS-TrackerAppTests/__Snapshots__/iOS_TrackerAppTests/testTrackersViewControllerDarkSnapshot.1.png
Скриншоты рекомендую не сохранять в репозиторий, они создадутся при запуске теста

2023-09-28 10:28 UTC, AndyKruch commented
Прошу принять критические правки по ревью. 

Остальное сделаю факультативно.

Спасибо!

2023-09-28 16:04 UTC, protos17 approved these changes

2023-09-28 16:04 UTC, protos17 commented on iOS-TrackerApp/iOS-TrackerAppTests/__Snapshots__/iOS_TrackerAppTests/testTrackersViewControllerDarkSnapshot.1.png
Сами скриншоты в репозитирой не нужно сохранять - они создадутся при запуске теста

2023-09-29 05:49 UTC, merged